title: My blog
author: addyionut
email: addyionut@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is an awesome 
blog
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  addyionut # DO NOT include the @ character, or else the build will fail!
show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
